Fix AttributeError with 'pyarrow' module when rkllm is used
'pyarrow' v21.0.0 removed the 'PyExtensionType' attribute, which causes
  AttributeError when the very old 'datasets' v2.14.6 module tries to
  reference this said attribute.

Since the 'rkllm-toolkit' wheel has a hardcoded dependency on 'datasets'
  v2.14.6, the only solution is to install 'pyarrow' v20.0.0 or earlier
  for now.

This fixes the following errors in Python when importing 'RKLLM' from 'rkllm.api':

Traceback (most recent call last):
  File "/root/toolkit/./interactive_pipeline.py", line 1, in <module>
    from rkllm.api import RKLLM
  File "/usr/local/lib/python3.10/dist-packages/rkllm/__init__.py", line 1, in <module>
    from rkllm import api
  File "/usr/local/lib/python3.10/dist-packages/rkllm/api/__init__.py", line 1, in <module>
    from rkllm.api.rkllm import RKLLM
  File "/usr/local/lib/python3.10/dist-packages/rkllm/api/rkllm.py", line 1, in <module>
    from rkllm.api.rkllm_base import RKLLMBase
  File "rkllm/api/rkllm_base.py", line 1, in init rkllm.api.rkllm_base
  File "rkllm/base/quantizer.py", line 12, in init rkllm.base.quantizer
  File "rkllm/base/loader.py", line 4, in init rkllm.base.loader
  File "/usr/local/lib/python3.10/dist-packages/datasets/__init__.py", line 22, in <module>
    from .arrow_dataset import Dataset
  File "/usr/local/lib/python3.10/dist-packages/datasets/arrow_dataset.py", line 67, in <module>
    from .arrow_writer import ArrowWriter, OptimizedTypedSequence
  File "/usr/local/lib/python3.10/dist-packages/datasets/arrow_writer.py", line 27, in <module>
    from .features import Features, Image, Value
  File "/usr/local/lib/python3.10/dist-packages/datasets/features/__init__.py", line 18, in <module>
    from .features import Array2D, Array3D, Array4D, Array5D, ClassLabel, Features, Sequence, Value
  File "/usr/local/lib/python3.10/dist-packages/datasets/features/features.py", line 634, in <module>
    class _ArrayXDExtensionType(pa.PyExtensionType):
AttributeError: module 'pyarrow' has no attribute 'PyExtensionType'. Did you mean: 'ExtensionType'?